pipeline {
  environment{
    USER_CREDENTIAL = credentials('devops')
    DOCKER_REPOSITORY = 'dockerdev.krugercorp.com'
    HELM_REPOSITORY = 'helm-internal'
    PROJECT_NAME = 'krg-bago-frontend'
    DEPLOY_CONTEXT = '/msBagoFrontend/'
    PROJECT_VERSION = '1.0.1'
  }

  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            app: test
        spec:
          hostAliases:
          - ip: "192.168.5.67"
            hostnames:
              - "nexusdev.krugercorp.com"
          - ip: "192.168.5.67"
            hostnames:
              - "dockerdev.krugercorp.com"
          containers:
          - name: node
            env:
              - name: 'HOME'
                value: '.'
            image: node:16.17.0-alpine3.16
            command:
            - cat
            tty: true
          - name: docker
            image: docker:20.10.18-cli-alpine3.16
            command:
            - cat
            tty: true
            volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
          - name: helm
            image: alpine/helm:3.10.0
            command:
            - cat
            tty: true
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
      '''
    }
  }
}
