export const HappyBirthdayService = [
  {
    id: 1,
    name: "Juan Sotomayor",
    birthday: "Abril 20",
    email: "juan_sotomayor@labsbago.com",
    phone: "1234567890",
    position: "Frontend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 2,
    name: "Jose Perez",
    birthday: "Abril 18",
    email: "jose_perez@labsbago.com",
    phone: "5054654654",
    position: "Backend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 3,
    name: "Andres Lopez",
    birthday: "Abril 05",
    email: "andres_lopez@labsbago.com",
    phone: "6546132134",
    position: "DevOps",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 4,
    name: "Esteban Smith",
    birthday: "Abril 26",
    email: "esteban_smith@labsbago.com",
    phone: "1234567890",
    position: "Frontend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 5,
    name: "Juan Sotomayor",
    birthday: "Abril 20",
    email: "juan_sotomayor@labsbago.com",
    phone: "1234567890",
    position: "Frontend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 6,
    name: "Jose Perez",
    birthday: "Abril 18",
    email: "jose_perez@labsbago.com",
    phone: "5054654654",
    position: "Backend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 7,
    name: "Andres Lopez",
    birthday: "Abril 05",
    email: "andres_lopez@labsbago.com",
    phone: "6546132134",
    position: "DevOps",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 8,
    name: "Esteban Smith",
    birthday: "Abril 26",
    email: "esteban_smith@labsbago.com",
    phone: "1234567890",
    position: "Frontend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
  {
    id: 9,
    name: "Juan Sotomayor",
    birthday: "Abril 20",
    email: "juan_sotomayor@labsbago.com",
    phone: "1234567890",
    position: "Frontend Developer",
    image: "https://i.imgur.com/3ZQ3YzB.jpg",
  },
];
